"""TransparencyLens — documentation, disclosure, contestability.

Checks for citations, uncited claims, assumptions, AI disclosure,
contestability mechanisms, and next steps.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING, Any

from modules.governance.constants import (
    DEFAULT_CONFIDENCE,
    GovernanceState,
)
from modules.governance.evidence import Evidence
from modules.governance.lenses.base import (
    get_lens_names_for_policy,
)
from modules.governance.verdict import (
    LensFinding,
    LensResult,
)

if TYPE_CHECKING:
    from modules.governance.engine import GovernanceEngine
    from modules.governance.loader import LoadedPolicy

# --- Transparency detection patterns ---

_I = re.IGNORECASE

CITATION_PATTERNS: list[re.Pattern[str]] = [
    re.compile(
        r"\[(?:source|ref|citation)"
        r"\s*:?\s*[^\]]+\]",
        _I,
    ),
    re.compile(r"according to\s+\w+", _I),
    re.compile(
        r"per\s+(?:section|article|regulation)"
        r"\s+\S+",
        _I,
    ),
    re.compile(
        r"\((?:NIST|ISO|EU|IEEE)\s+[^)]+\)", _I
    ),
    re.compile(r"§\s*\d+", _I),
]

CLAIM_PATTERNS: list[re.Pattern[str]] = [
    re.compile(
        r"\b(?:studies show|research"
        r" (?:shows|indicates|suggests))\b",
        _I,
    ),
    re.compile(
        r"\b(?:it is (?:known|proven"
        r"|established) that)\b",
        _I,
    ),
    re.compile(
        r"\b(?:experts agree|consensus is)\b",
        _I,
    ),
    re.compile(
        r"\b(?:data shows|evidence suggests)\b",
        _I,
    ),
    re.compile(
        r"\b(?:statistically|empirically)\b", _I
    ),
]

ASSUMPTION_PATTERNS: list[re.Pattern[str]] = [
    re.compile(
        r"\b(?:assuming|assumption|we assume)\b",
        _I,
    ),
    re.compile(
        r"\b(?:this assumes|given that"
        r"|provided that)\b",
        _I,
    ),
    re.compile(r"\bnote:?\s", _I),
    re.compile(r"\bcaveat:?\s", _I),
]

HIDDEN_ASSUMPTION_PATTERNS: list[re.Pattern[str]] = [
    re.compile(
        r"\b(?:obviously|clearly|naturally"
        r"|of course)\b",
        _I,
    ),
    re.compile(
        r"\b(?:everyone knows"
        r"|it goes without saying)\b",
        _I,
    ),
    re.compile(
        r"\b(?:needless to say"
        r"|self-evident)\b",
        _I,
    ),
    re.compile(
        r"\b(?:trivially|simply put)\b", _I
    ),
]

CONTESTABILITY_PATTERNS: list[re.Pattern[str]] = [
    re.compile(
        r"\b(?:appeal|contest|dispute"
        r"|challenge)\b",
        _I,
    ),
    re.compile(
        r"\b(?:review process|grievance"
        r"|recourse)\b",
        _I,
    ),
    re.compile(
        r"\b(?:if you disagree"
        r"|to contest this)\b",
        _I,
    ),
    re.compile(
        r"\b(?:human review|manual review)\b",
        _I,
    ),
]

AI_DISCLOSURE_PATTERNS: list[re.Pattern[str]] = [
    re.compile(
        r"\b(?:generated by|powered by"
        r"|assisted by)\s+(?:AI|artificial"
        r" intelligence|machine learning)\b",
        _I,
    ),
    re.compile(
        r"\b(?:AI[- ]generated"
        r"|machine[- ]generated|automated)\b",
        _I,
    ),
    re.compile(
        r"\b(?:this (?:response|output|content)"
        r" (?:was|is) (?:generated|produced"
        r"|created) by)\b",
        _I,
    ),
    re.compile(
        r"\b(?:large language model"
        r"|LLM|chatbot)\b",
        _I,
    ),
]

NEXT_STEPS_PATTERNS: list[re.Pattern[str]] = [
    re.compile(
        r"\b(?:next steps|action items"
        r"|follow[- ]up)\b",
        _I,
    ),
    re.compile(
        r"\b(?:to proceed|going forward"
        r"|moving forward)\b",
        _I,
    ),
    re.compile(
        r"\b(?:recommended actions"
        r"|suggested next)\b",
        _I,
    ),
]


def has_citations(content: str) -> list[str]:
    """Check if content contains citations."""
    hits: list[str] = []
    for pat in CITATION_PATTERNS:
        m = pat.search(content)
        if m:
            hits.append(m.group())
    return hits


def check_uncited_claims(content: str) -> list[str]:
    """Detect claims that lack citations."""
    claims: list[str] = []
    citations = has_citations(content)
    for pat in CLAIM_PATTERNS:
        m = pat.search(content)
        if m and not citations:
            claims.append(m.group())
    return claims


def has_explicit_assumptions(content: str) -> list[str]:
    """Check for explicitly stated assumptions."""
    hits: list[str] = []
    for pat in ASSUMPTION_PATTERNS:
        m = pat.search(content)
        if m:
            hits.append(m.group())
    return hits


def check_hidden_assumptions(content: str) -> list[str]:
    """Detect hidden assumptions (weasel words)."""
    hits: list[str] = []
    for pat in HIDDEN_ASSUMPTION_PATTERNS:
        m = pat.search(content)
        if m:
            hits.append(m.group())
    return hits


def has_contestability(content: str) -> list[str]:
    """Check for contestability mechanisms."""
    hits: list[str] = []
    for pat in CONTESTABILITY_PATTERNS:
        m = pat.search(content)
        if m:
            hits.append(m.group())
    return hits


def has_ai_disclosure(content: str) -> list[str]:
    """Check for AI disclosure statements."""
    hits: list[str] = []
    for pat in AI_DISCLOSURE_PATTERNS:
        m = pat.search(content)
        if m:
            hits.append(m.group())
    return hits


def has_next_steps(content: str) -> list[str]:
    """Check for next steps / action items."""
    hits: list[str] = []
    for pat in NEXT_STEPS_PATTERNS:
        m = pat.search(content)
        if m:
            hits.append(m.group())
    return hits


class TransparencyLens:
    """Evaluates documentation, disclosure, interpretability.

    Checks for:
    - Hidden assumptions -> ESCALATE
    - Uncited claims -> ESCALATE
    - Missing AI disclosure (positive signal when present)
    - Missing contestability (positive signal when present)
    - Engine rule evaluation -> per-rule status
    """

    def __init__(
        self,
        engine: GovernanceEngine | None = None,
    ) -> None:
        self._engine = engine

    @property
    def name(self) -> str:
        return "transparency"

    def _get_engine(self) -> GovernanceEngine:
        if self._engine is None:
            from modules.governance.engine import (
                GovernanceEngine,
            )

            self._engine = GovernanceEngine()
        return self._engine

    def _calculate_confidence(
        self,
        evidence_count: int,
        *,
        uncertain: bool = False,
    ) -> float:
        """Calculate confidence with penalties.

        Penalties:
        - satisfied, no evidence: -0.04
        - satisfied, 1 evidence: -0.02
        - uncertain: -0.12
        """
        conf = DEFAULT_CONFIDENCE
        if uncertain:
            conf -= 0.12
        elif evidence_count == 0:
            conf -= 0.04
        elif evidence_count == 1:
            conf -= 0.02
        return max(0.0, round(conf, 2))

    def evaluate(
        self,
        artifact: dict[str, Any],
        policies: list[LoadedPolicy],
    ) -> LensResult:
        content = str(artifact.get("design", artifact))
        findings: list[LensFinding] = []

        # 1. Hidden assumptions -> ESCALATE
        hidden = check_hidden_assumptions(content)
        if hidden:
            findings.append(
                LensFinding(
                    lens=self.name,
                    status=GovernanceState.ESCALATE,
                    policy_id="transparency-hidden-assumptions",
                    message=(
                        "Hidden assumptions detected "
                        "(weasel words)"
                    ),
                    evidence=[
                        Evidence(
                            claim=f"Hidden assumption: {h}",
                            source="artifact",
                            pointer="design",
                        )
                        for h in hidden
                    ],
                    confidence=self._calculate_confidence(
                        len(hidden), uncertain=True
                    ),
                )
            )

        # 2. Uncited claims -> ESCALATE
        uncited = check_uncited_claims(content)
        if uncited:
            findings.append(
                LensFinding(
                    lens=self.name,
                    status=GovernanceState.ESCALATE,
                    policy_id="transparency-uncited-claims",
                    message="Claims made without citations",
                    evidence=[
                        Evidence(
                            claim=f"Uncited: {c}",
                            source="artifact",
                            pointer="design",
                        )
                        for c in uncited
                    ],
                    confidence=self._calculate_confidence(
                        len(uncited), uncertain=True
                    ),
                )
            )

        # 3. Positive signals (informational findings)
        citations = has_citations(content)
        if citations:
            findings.append(
                LensFinding(
                    lens=self.name,
                    status=GovernanceState.PASS,
                    policy_id="transparency-citations",
                    message=(
                        f"Citations found: {len(citations)}"
                    ),
                    evidence=[
                        Evidence(
                            claim="Citation present",
                            source="artifact",
                            pointer="design",
                            excerpt=c[:60],
                        )
                        for c in citations
                    ],
                    confidence=self._calculate_confidence(
                        len(citations)
                    ),
                )
            )

        assumptions = has_explicit_assumptions(content)
        if assumptions:
            findings.append(
                LensFinding(
                    lens=self.name,
                    status=GovernanceState.PASS,
                    policy_id="transparency-assumptions",
                    message="Explicit assumptions declared",
                    evidence=[
                        Evidence(
                            claim=f"Assumption: {a}",
                            source="artifact",
                            pointer="design",
                        )
                        for a in assumptions
                    ],
                    confidence=self._calculate_confidence(
                        len(assumptions)
                    ),
                )
            )

        # 4. Delegate to engine for policy rule evaluation
        engine = self._get_engine()
        for policy in policies:
            if self.name not in get_lens_names_for_policy(
                policy
            ):
                continue
            results = engine.evaluate(
                artifact, policy.rules
            )
            for cr in results:
                findings.append(
                    LensFinding(
                        lens=self.name,
                        status=cr.status,
                        policy_id=policy.id,
                        message=cr.message,
                        evidence=[
                            Evidence(
                                claim=cr.message,
                                source="policy",
                                pointer=policy.id,
                            )
                        ],
                        confidence=self._calculate_confidence(
                            1
                        ),
                    )
                )

        return LensResult(
            lens=self.name, findings=findings
        )
