/**
 * Shared frontend types.
 * API types are generated by orval in lib/api/.
 */

export interface WorkspaceNav {
  id: string;
  name: string;
  projects: ProjectNav[];
}

export interface ProjectNav {
  id: string;
  name: string;
  governanceScore: number;
}
