"""Handoff limits and cooldowns."""

MAX_HANDOFFS_PER_REQUEST = 3
MAX_HANDOFFS_PER_PIPELINE = 10
HANDOFF_TIMEOUT_MS = 5000
EXPORT_HANDOFF_TIMEOUT_MS = 8000
ROUTER_TIMEOUT_MS = 500
HANDOFF_COOLDOWN_MS = 2000
CIRCULAR_DETECTION_WINDOW = 3
