"""Generate GitHub Actions governance check workflow.

Pure generator — no I/O, no database dependency.
"""

from __future__ import annotations

import structlog

log = structlog.get_logger()

DEFAULT_PASS_THRESHOLD = 90  # percentage
DEFAULT_NODE_VERSION = "22"


class CIWorkflowGenerator:
    """Generate GitHub Actions governance check workflow."""

    def generate(
        self,
        project_name: str,
        eval_criteria_path: str = "ideanance/eval-criteria.yml",
        frameworks: list[str] | None = None,
        pass_threshold: int = DEFAULT_PASS_THRESHOLD,
    ) -> str:
        """Generate a GitHub Actions YAML workflow string."""
        log.info(
            "ci_generator.generating",
            project=project_name,
            threshold=pass_threshold,
        )
        frameworks = frameworks or []
        fw_label = ", ".join(frameworks) if frameworks else "All"

        return self._render_workflow(
            project_name, eval_criteria_path, fw_label, pass_threshold
        )

    def _render_workflow(
        self,
        project_name: str,
        eval_criteria_path: str,
        framework_label: str,
        pass_threshold: int,
    ) -> str:
        """Render the workflow as YAML string."""
        js_calc = (
            "const r = require('./results.json');"
            "const s = r.results.stats;"
            "console.log(Math.round("
            "s.successes / (s.successes + s.failures) * 100));"
        )
        err_msg = (
            "::error::Governance check FAILED: "
            "${PASS_RATE}% < "
            f"{pass_threshold}%"
        )
        return (
            f'# Generated by Ideanance for "{project_name}"\n'
            f"# Frameworks: {framework_label}\n"
            f"name: Governance Check\n"
            f"\n"
            f"on:\n"
            f"  pull_request:\n"
            f"    paths:\n"
            f"      - 'src/agents/**'\n"
            f"      - 'ideanance/**'\n"
            f"\n"
            f"jobs:\n"
            f"  governance:\n"
            f"    runs-on: ubuntu-latest\n"
            f"    steps:\n"
            f"      - uses: actions/checkout@v4\n"
            f"\n"
            f"      - uses: actions/setup-node@v4\n"
            f"        with:\n"
            f'          node-version: "{DEFAULT_NODE_VERSION}"\n'
            f"\n"
            f"      - name: Run governance eval criteria\n"
            f"        env:\n"
            f"          ANTHROPIC_API_KEY:"
            f" ${{{{ secrets.ANTHROPIC_API_KEY }}}}\n"
            f"        run: |\n"
            f"          npx promptfoo@latest eval \\\n"
            f"            -c {eval_criteria_path} \\\n"
            f"            -o results.json\n"
            f"\n"
            f"      - name: Check governance pass rate\n"
            f"        run: |\n"
            f'          PASS_RATE=$(node -e "{js_calc}")\n'
            f'          echo "Governance pass rate:'
            f' ${{PASS_RATE}}%"\n'
            f'          if [ "$PASS_RATE" -lt '
            f"{pass_threshold} ]; then\n"
            f'            echo "{err_msg}"\n'
            f"            exit 1\n"
            f"          fi\n"
        )

    def _build_steps(
        self,
        project_name: str,
        eval_criteria_path: str,
        framework_label: str,
        pass_threshold: int,
    ) -> list[dict]:
        """Build the steps list for the workflow."""
        return [
            {"uses": "actions/checkout@v4"},
            {
                "uses": "actions/setup-node@v4",
                "with": {"node-version": DEFAULT_NODE_VERSION},
            },
            {
                "name": "Run governance eval criteria",
                "env": {
                    "ANTHROPIC_API_KEY": (
                        "${{ secrets.ANTHROPIC_API_KEY }}"
                    )
                },
                "run": (
                    f"npx promptfoo@latest eval "
                    f"-c {eval_criteria_path} "
                    f"-o results.json"
                ),
            },
            {
                "name": "Check governance pass rate",
                "run": (
                    f"echo 'Governance threshold:"
                    f" {pass_threshold}%'"
                ),
            },
        ]
